<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FTR3COF93BK8A76" name="testcases.APP_GUI" tests="1" failures="1" timestamp="10 Mar 2021 03:06:49 GMT" time="60.276" errors="0">
  <testcase name="APP_GUI_21_Mattermost_Test" time="60.276" classname="testcases.APP_GUI">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	@@line_start [3935] line_end; expected [UI_app_testLogic is start.
Are you 18?
1. Yes
2. No] but found [Missed that. Let me ask you in a different way. Is it water then?] expected [true] but found [false],
	@@line_start [3939] line_end; expected [UI_app_testLogic is start.
Of course, will be soon.] but found [Yes!
] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	@@line_start [3935] line_end; expected [UI_app_testLogic is start.
Are you 18?
1. Yes
2. No] but found [Missed that. Let me ask you in a different way. Is it water then?] expected [true] but found [false],
	@@line_start [3939] line_end; expected [UI_app_testLogic is start.
Of course, will be soon.] but found [Yes!
] expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.APP_GUI.APP_GUI_21_Mattermost_Test(APP_GUI.java:3954)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- APP_GUI_21_Mattermost_Test -->
</testsuite> <!-- testcases.APP_GUI -->
