<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FTR3COF93BK8A76" ignored="6" name="Default test" tests="1" failures="1" timestamp="2022-03-24T22:50:40 EDT" time="48.34" errors="0">
  <testcase name="DT_07" time="14.935" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	@@line_start [526] line_end; expected [SVC ORD CBDT] but found [CBDT PAYING 4 TT]gui_start  gui_end,
	@@line_start [532] line_end; expected [TT has been added to the customer&amp;apos;s line in the switch.] but found [Inform the customer that the trouble will be cleared by 03-26-22 0500P.]gui_start  gui_end">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
@@line_start [526] line_end; expected [SVC ORD CBDT] but found [CBDT PAYING 4 TT]gui_start  gui_end,
@@line_start [532] line_end; expected [TT has been added to the customer's line in the switch.] but found [Inform the customer that the trouble will be cleared by 03-26-22 0500P.]gui_start  gui_end
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.WFA_POTS_Dial_Tone_1.DT_07(WFA_POTS_Dial_Tone_1.java:556)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- DT_07 -->
  <testcase name="DT_05" time="0.0" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <ignored/>
  </testcase> <!-- DT_05 -->
  <testcase name="DT_01" time="0.0" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <ignored/>
  </testcase> <!-- DT_01 -->
  <testcase name="DT_06" time="0.0" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <ignored/>
  </testcase> <!-- DT_06 -->
  <testcase name="DT_04" time="0.0" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <ignored/>
  </testcase> <!-- DT_04 -->
  <testcase name="DT_03" time="0.0" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <ignored/>
  </testcase> <!-- DT_03 -->
  <testcase name="DT_02" time="0.0" classname="TestCases.WFA_POTS_Dial_Tone_1">
    <ignored/>
  </testcase> <!-- DT_02 -->
</testsuite> <!-- Default test -->
